from __future__ import annotations
from guardian.reporters.base import Reporter
from guardian.core.models import ScanResult, Severity


class HtmlReporter(Reporter):
    SEVERITY_COLORS = {
        Severity.ERROR: ("#dc2626", "#fee2e2"),
        Severity.WARNING: ("#d97706", "#fef3c7"),
        Severity.INFO: ("#2563eb", "#dbeafe"),
    }

    def _build_html(self, result: ScanResult) -> str:
        items_html = ""
        for i, issue in enumerate(result.issues, 1):
            color, bg = self.SEVERITY_COLORS.get(
                issue.severity, ("#6b7280", "#f3f4f6")
            )
            items_html += f"""
            <tr style="background: {bg}">
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb;">#{i}</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb;">
                    <span style="display: inline-block; padding: 2px 8px; border-radius: 4px;
                         color: white; background: {color}; font-size: 12px; font-weight: 600;">
                        {issue.severity.value.upper()}
                    </span>
                </td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-family: monospace; color: {color};">
                    {issue.rule_id}
                </td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb;">{issue.message}</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-family: monospace; font-size: 13px;">
                    <code>{issue.file_path}:{issue.line}</code>
                </td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-size: 13px; color: #059669;">
                    {issue.suggestion or "-"}
                </td>
            </tr>"""

        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>QualiGuard Scan Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #f8fafc; color: #1e293b; padding: 40px; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ font-size: 28px; font-weight: 700; margin-bottom: 8px; }}
        .subtitle {{ color: #64748b; margin-bottom: 24px; }}
        .summary {{ display: flex; gap: 16px; margin-bottom: 32px; }}
        .stat {{ flex: 1; background: white; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .stat-value {{ font-size: 32px; font-weight: 700; }}
        .stat-label {{ font-size: 14px; color: #64748b; margin-top: 4px; }}
        table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 12px;
                overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        th {{ text-align: left; padding: 12px 10px; font-size: 13px; font-weight: 600;
             color: #64748b; text-transform: uppercase; border-bottom: 2px solid #e5e7eb; }}
        td {{ vertical-align: top; }}
        code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 3px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>QualiGuard 代码质量报告</h1>
        <p class="subtitle">扫描目标: {result.target} | 文件: {result.scanned_files}/{result.total_files}</p>

        <div class="summary">
            <div class="stat">
                <div class="stat-value" style="color: #dc2626;">{result.error_count}</div>
                <div class="stat-label">严重错误 Errors</div>
            </div>
            <div class="stat">
                <div class="stat-value" style="color: #d97706;">{result.warning_count}</div>
                <div class="stat-label">警告 Warnings</div>
            </div>
            <div class="stat">
                <div class="stat-value" style="color: #2563eb;">{result.info_count}</div>
                <div class="stat-label">提示 Info</div>
            </div>
            <div class="stat">
                <div class="stat-value">{len(result.issues)}</div>
                <div class="stat-label">总计 Total</div>
            </div>
        </div>

        <table>
            <thead>
                <tr><th>#</th><th>级别</th><th>规则</th><th>描述</th><th>位置</th><th>建议</th></tr>
            </thead>
            <tbody>
                {items_html}
            </tbody>
        </table>
        <p style="text-align: center; margin-top: 24px; color: #94a3b8; font-size: 13px;">
            Generated by QualiGuard v0.1.0
        </p>
    </div>
</body>
</html>"""

    def generate(self, result: ScanResult, output_path: str | None = None) -> str:
        output = self._build_html(result)
        if output_path:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(output)
        return output
